# Generated by Django 4.2.7 on 2023-11-01 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorcti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestorcti.facultad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestorcti.departamento'),
        ),
    ]
