# Generated by Django 4.2.7 on 2023-11-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorcti', '0002_alter_departamento_facultad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(blank=True, max_length=50)),
                ('otorgado_por', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('nombre_reconocimiento', models.CharField(blank=True, max_length=200)),
                ('causa', models.CharField(blank=True, max_length=500)),
                ('autores', models.ManyToManyField(blank=True, null=True, to='gestorcti.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(blank=True, max_length=50)),
                ('otorgado_por', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('denominacion', models.CharField(blank=True, max_length=200)),
                ('titulo_resultado', models.CharField(blank=True, max_length=500)),
                ('sector_estrategico', models.CharField(blank=True, max_length=200)),
                ('nombre_evento', models.CharField(blank=True, max_length=200)),
                ('autores', models.ManyToManyField(blank=True, null=True, to='gestorcti.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('ano', models.IntegerField(blank=True)),
                ('pais', models.CharField(blank=True, max_length=30)),
                ('formato', models.BooleanField(blank=True, default=1)),
                ('link', models.URLField(blank=True)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('editorial', models.CharField(max_length=500)),
                ('paginas', models.IntegerField()),
                ('isbn', models.CharField(max_length=200)),
                ('autores', models.ManyToManyField(blank=True, null=True, to='gestorcti.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('ano', models.IntegerField(blank=True)),
                ('pais', models.CharField(blank=True, max_length=30)),
                ('formato', models.BooleanField(blank=True, default=1)),
                ('link', models.URLField(blank=True)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('editorial', models.CharField(blank=True, max_length=500)),
                ('paginas', models.IntegerField(blank=True)),
                ('isbn', models.CharField(blank=True, max_length=200)),
                ('autores', models.ManyToManyField(blank=True, null=True, to='gestorcti.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('ano', models.IntegerField(blank=True)),
                ('pais', models.CharField(blank=True, max_length=30)),
                ('formato', models.BooleanField(blank=True, default=1)),
                ('link', models.URLField(blank=True)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('issn', models.CharField(blank=True, max_length=10)),
                ('paginas', models.CharField(blank=True, max_length=30)),
                ('titulo_revista', models.CharField(blank=True, max_length=200)),
                ('volumen', models.CharField(blank=True, max_length=30)),
                ('bd_referenciada', models.CharField(blank=True, max_length=30)),
                ('area_conocimiento', models.CharField(blank=True, max_length=200)),
                ('factor_impacto', models.CharField(blank=True, max_length=200)),
                ('autores', models.ManyToManyField(blank=True, null=True, to='gestorcti.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
