# Generated by Django 4.2.7 on 2023-11-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorcti', '0003_reconocimiento_premio_monografia_libro_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='estado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='monografia',
            name='estado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='premio',
            name='estado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='estado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
