# Generated by Django 4.2.7 on 2023-11-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorcti', '0004_articulo_estado_libro_estado_monografia_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='titulo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
