# Generated by Django 4.2.7 on 2023-11-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorcti', '0005_alter_articulo_titulo_alter_libro_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='autores',
            field=models.ManyToManyField(blank=True, to='gestorcti.usuario'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(blank=True, to='gestorcti.usuario'),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='autores',
            field=models.ManyToManyField(blank=True, to='gestorcti.usuario'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='autores',
            field=models.ManyToManyField(blank=True, to='gestorcti.usuario'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='autores',
            field=models.ManyToManyField(blank=True, to='gestorcti.usuario'),
        ),
    ]
