# Generated by Django 4.2.7 on 2023-11-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorcti', '0006_usuario_correo_alter_articulo_autores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombreUsuario',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
