# Generated by Django 4.2.7 on 2023-11-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorcti', '0007_usuario_nombreusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
